services:
  - type: web
    name: astral-architect-io
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: GITHUB_TOKEN
        sync: false
      - key: MEDIUM_USERNAME
        value: "@ragul.mr3391"
      - key: GOOGLE_API_KEY
        sync: false
